---
images:
  pod_template:
    repository: localhost:5000/airflow_python
    tag: latest
    pullPolicy: IfNotPresent
executor: "KubernetesExecutor"
dags:
  gitSync:
    enabled: true

    repo: https://github.com/ankiyong/seoul_traffic.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"

    period: 5s
    credentialsSecret: git-credentials
    sshKeySecret: airflow-git-ssh-secret
    containerName: git-sync
    uid: 65533